"""empty message

Revision ID: d9a39025c966
Revises: 42d8a6a9f96f
Create Date: 2020-08-07 12:28:15.262350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a39025c966'
down_revision = '42d8a6a9f96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('cik_number', sa.String(), nullable=True))
    op.drop_column('company', 'cik_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('cik_num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('company', 'cik_number')
    # ### end Alembic commands ###
